### ISSUE TITLE
Portfolio: Application Deploy

### ISSUE THREAD

**Issue by ger619** [ger619/Portfolio-mobile-version#6]
Deploy website using GitHub Pages.

- Check the online version of your portfolio and make sure that the page works properly.

- Updated the README of your repository to include a link to the online version.

- Otherwise, submit a link to the PR with changes required for the deployment.

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi @, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] You submitted the wrong link Please make a new branch for your project deployment with GitHub pages then make a pull request and ask for the review with your Pull Request link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by ger619** [comment]
Hello @Omar-Muhamad 
thank you for this 
regards
